# Generated by Django 4.0.5 on 2022-07-28 05:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('firstName', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('middleName', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('lastName', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('is_nonmember', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_judge', models.BooleanField(default=False)),
                ('is_bidder', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_inactive', models.DateTimeField(blank=True, null=True, verbose_name='date inactive')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
